---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-config
data:
  daemon.json: |
    {
      "hosts": [ "unix:///var/run/docker.sock",
                 "unix:///var/run/codefresh/docker.sock",
                 "tcp://0.0.0.0:1300"],
      "storage-driver": "overlay",
      "storage-opts": ["overlay.override_kernel_check=1"],
      "metrics-addr" : "0.0.0.0:9323",
      "experimental" : true
    }
