version: '2'
services:
    cadvisor:
      image: google/cadvisor:v0.25.0
      labels:
          - internal=true
      volumes:
          - '/:/rootfs:ro'
          - '/var/run:/var/run:rw'
          - '/sys:/sys:ro'
          - '/var/lib/docker/:/var/lib/docker:ro'
      ports:
          - '8080:8080'

    prometheus:
      image: 'prom/prometheus:v1.6.3'
      labels:
          - "internal=true"
      volumes:
          - '/mnt/sda1/prometheus/data/prometheus:/prometheus:rw'
          - '${PWD}/etc/prometheus:/etc/prometheus:rw'
      # network_mode: host
      ports:
          - '9090:9090'
      command:
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-storage.local.path=/prometheus'
          - '-alertmanager.url=http://alertmanager:9093'
          - '-web.external-url=http://192.168.99.100:9090/'
          - '-query.staleness-delta=15s'
      # ' -query.staleness-delta=15s -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -alertmanager.url=http://alertmanager:9093 -web.external-url=http://192.168.99.100:9090/'
    # not mandatory
    alertmanager:
      image: 'prom/alertmanager'
      labels:
          - "internal=true"
      volumes:
          - '${PWD}/data/alertmanager:/alertmanager:rw'
          - '${PWD}/etc/alertmanager:/etc/alertmanager:ro'
      ports:
          - '9093:9093'

    grafana:
      image: 'grafana/grafana'
      labels:
          - io.codefresh.owner=codefresh
      volumes:
          - '/mnt/sda1/prometheus/data/grafana:/var/lib/grafana'
      environment:
          GF_SECURITY_ADMIN_PASSWORD: a12345
      ports:
          - '3000:3000'
